// <auto-generated />
using System;
using DisenioMurosAyG.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DisenioMurosAyG.Migrations
{
    [DbContext(typeof(ControlContext))]
    [Migration("20200803185632_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ControlUsuariosProyectos.AplicacionSVG", b =>
                {
                    b.Property<string>("AplicacionId")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("AplicacionName")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Version")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.HasKey("AplicacionId");

                    b.ToTable("Aplicaciones");

                    b.HasData(
                        new
                        {
                            AplicacionId = "109958ab-e6fa-4a76-b531-e1b3f5c47bcb",
                            AplicacionName = "Diseño de muros AyG",
                            Version = "1.00"
                        });
                });

            modelBuilder.Entity("ControlUsuariosProyectos.Operacion", b =>
                {
                    b.Property<string>("OperationId")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("AplicacionId")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("FinOperacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InicioOperacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpV4")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IpV6")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.HasKey("OperationId");

                    b.HasIndex("AplicacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Operaciones");

                    b.HasData(
                        new
                        {
                            OperationId = "0c3abe28-6a2d-4474-a780-556c8053aba8",
                            AplicacionId = "109958ab-e6fa-4a76-b531-e1b3f5c47bcb",
                            FinOperacion = new DateTime(2020, 8, 3, 14, 56, 32, 140, DateTimeKind.Local).AddTicks(7120),
                            InicioOperacion = new DateTime(2020, 8, 3, 13, 56, 32, 139, DateTimeKind.Local).AddTicks(7110),
                            IpV4 = "172.17.98.33",
                            IpV6 = "::ffff:172.17.98.33",
                            UsuarioId = "699960b2-760f-49fe-bc24-038c142efbfe"
                        },
                        new
                        {
                            OperationId = "7d21cbde-acfa-4804-a810-f3ece1be9cfa",
                            AplicacionId = "109958ab-e6fa-4a76-b531-e1b3f5c47bcb",
                            FinOperacion = new DateTime(2020, 8, 3, 14, 56, 32, 140, DateTimeKind.Local).AddTicks(7120),
                            InicioOperacion = new DateTime(2020, 8, 3, 13, 56, 32, 140, DateTimeKind.Local).AddTicks(7120),
                            IpV4 = "172.17.98.33",
                            IpV6 = "::ffff:172.17.98.33",
                            UsuarioId = "7c245515-c73b-4eaf-960e-8edfb3b3daa4"
                        });
                });

            modelBuilder.Entity("ControlUsuariosProyectos.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioMail")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("UsuarioName")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("UsuarioTel")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = "699960b2-760f-49fe-bc24-038c142efbfe",
                            Password = "Bucefalo_1205",
                            Rol = 0,
                            UsuarioMail = "santivasquez1@gmail.com",
                            UsuarioName = "Santiago Vasquez Gomez"
                        },
                        new
                        {
                            UsuarioId = "7c245515-c73b-4eaf-960e-8edfb3b3daa4",
                            Password = "12345",
                            Rol = 1,
                            UsuarioMail = "anabadillo@agingenieria.com.co",
                            UsuarioName = "Ana Badillo"
                        });
                });

            modelBuilder.Entity("ControlUsuariosProyectos.Operacion", b =>
                {
                    b.HasOne("ControlUsuariosProyectos.AplicacionSVG", "Aplicacion")
                        .WithMany()
                        .HasForeignKey("AplicacionId");

                    b.HasOne("ControlUsuariosProyectos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
