namespace DisenioMurosAyG.Views
{
    partial class InformacionAlzadoView1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Telerik.WinControls.UI.GridViewComboBoxColumn gridViewComboBoxColumn1 = new Telerik.WinControls.UI.GridViewComboBoxColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition1 = new Telerik.WinControls.UI.TableViewDefinition();
            this.enumBinder1 = new Telerik.WinControls.UI.Data.EnumBinder();
            this.radThemeManager1 = new Telerik.WinControls.RadThemeManager();
            this.materialBlueGreyTheme1 = new Telerik.WinControls.Themes.MaterialBlueGreyTheme();
            this.gbAlzadoGeneral = new Telerik.WinControls.UI.RadGroupBox();
            this.dgAlzado = new Telerik.WinControls.UI.RadGridView();
            ((System.ComponentModel.ISupportInitialize)(this.gbAlzadoGeneral)).BeginInit();
            this.gbAlzadoGeneral.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgAlzado)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgAlzado.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            this.SuspendLayout();
            // 
            // enumBinder1
            // 
            this.enumBinder1.Source = typeof(Entidades.GradoDisipacionEnergia);
            gridViewComboBoxColumn1.DataSource = this.enumBinder1;
            gridViewComboBoxColumn1.DataType = typeof(Entidades.GradoDisipacionEnergia);
            gridViewComboBoxColumn1.DisplayMember = "Description";
            gridViewComboBoxColumn1.FieldName = "GradoDisipacionEnergia";
            gridViewComboBoxColumn1.HeaderText = "GradoDisipacionEnergia";
            gridViewComboBoxColumn1.IsAutoGenerated = true;
            gridViewComboBoxColumn1.Name = "GradoDisipacionEnergia";
            gridViewComboBoxColumn1.ValueMember = "Value";
            this.enumBinder1.Target = gridViewComboBoxColumn1;
            // 
            // gbAlzadoGeneral
            // 
            this.gbAlzadoGeneral.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this.gbAlzadoGeneral.Controls.Add(this.dgAlzado);
            this.gbAlzadoGeneral.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gbAlzadoGeneral.HeaderText = "Información general alzado muros ";
            this.gbAlzadoGeneral.Location = new System.Drawing.Point(0, 0);
            this.gbAlzadoGeneral.Name = "gbAlzadoGeneral";
            this.gbAlzadoGeneral.Size = new System.Drawing.Size(956, 576);
            this.gbAlzadoGeneral.TabIndex = 0;
            this.gbAlzadoGeneral.Text = "Información general alzado muros ";
            this.gbAlzadoGeneral.ThemeName = "MaterialBlueGrey";
            // 
            // dgAlzado
            // 
            this.dgAlzado.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dgAlzado.Location = new System.Drawing.Point(12, 32);
            // 
            // 
            // 
            this.dgAlzado.MasterTemplate.ViewDefinition = tableViewDefinition1;
            this.dgAlzado.Name = "dgAlzado";
            this.dgAlzado.Size = new System.Drawing.Size(930, 532);
            this.dgAlzado.TabIndex = 0;
            this.dgAlzado.ThemeName = "MaterialBlueGrey";
            // 
            // InformacionAlzadoView1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(956, 576);
            this.Controls.Add(this.gbAlzadoGeneral);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "InformacionAlzadoView1";
            // 
            // 
            // 
            this.RootElement.ApplyShapeToControl = true;
            this.Text = "RadForm2";
            this.ThemeName = "MaterialBlueGrey";
            ((System.ComponentModel.ISupportInitialize)(this.gbAlzadoGeneral)).EndInit();
            this.gbAlzadoGeneral.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgAlzado.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgAlzado)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.RadThemeManager radThemeManager1;
        private Telerik.WinControls.Themes.MaterialBlueGreyTheme materialBlueGreyTheme1;
        public Telerik.WinControls.UI.RadGroupBox gbAlzadoGeneral;
        private Telerik.WinControls.UI.Data.EnumBinder enumBinder1;
        public Telerik.WinControls.UI.RadGridView dgAlzado;
    }
}
